// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'C:/Users/remember/Desktop/Prozen/docs/component/addProzen.md?type=frontmatter';
import { demoIndex as dmi0 } from 'C:/Users/remember/Desktop/Prozen/docs/component/addProzen.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'C:/Users/remember/Desktop/Prozen/docs/changelog/index.md?type=frontmatter';
import { demoIndex as dmi1 } from 'C:/Users/remember/Desktop/Prozen/docs/changelog/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'C:/Users/remember/Desktop/Prozen/docs/index.md?type=frontmatter';
import { demoIndex as dmi2 } from 'C:/Users/remember/Desktop/Prozen/docs/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'C:/Users/remember/Desktop/Prozen/packages/button/index.md?type=frontmatter';
import { demoIndex as dmi3 } from 'C:/Users/remember/Desktop/Prozen/packages/button/index.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from 'C:/Users/remember/Desktop/Prozen/packages/card/index.md?type=frontmatter';
import { demoIndex as dmi4 } from 'C:/Users/remember/Desktop/Prozen/packages/card/index.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from 'C:/Users/remember/Desktop/Prozen/packages/message/index.md?type=frontmatter';
import { demoIndex as dmi5 } from 'C:/Users/remember/Desktop/Prozen/packages/message/index.md?type=demo-index';

export const filesMeta = {
  'docs/component/addProzen': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/remember/Desktop/Prozen/docs/component/addProzen.md?type=text'),
  },
  'docs/changelog/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/remember/Desktop/Prozen/docs/changelog/index.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'C:/Users/remember/Desktop/Prozen/docs/index.md?type=text'),
  },
  'components/button/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'C:/Users/remember/Desktop/Prozen/packages/button/index.md?type=text'),
  },
  'components/card/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'C:/Users/remember/Desktop/Prozen/packages/card/index.md?type=text'),
  },
  'components/message/index': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'C:/Users/remember/Desktop/Prozen/packages/message/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
