// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { warning } from 'C:/Users/remember/Desktop/Prozen/node_modules/.pnpm/rc-util@5.44.4_react-dom@19.1.1_react@19.1.1__react@19.1.1/node_modules/rc-util';
import { SiteContext, type ISiteContext } from 'C:/Users/remember/Desktop/Prozen/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.2_514b76374320fa6069ce5d765ad00d76/node_modules/dumi/dist/client/theme-api/context.js';
import { components } from '../meta/atoms';
import { locales } from '../locales/config';



const entryExports = {
};

// Static content
const pkg = {"name":"Prozen","description":"","version":"1.0.0","license":"ISC","author":""};
const historyType = "browser";
const hostname = undefined;
const themeConfig = {"footer":"Copyright © 2025 | remember","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"logo":"https://youke1.picui.cn/s1/2025/08/19/68a4948e18150.png","title":"Prozen","nav":{"zh-CN":[{"title":"文档","link":"/docs/component"},{"title":"组件","link":"/components"},{"title":"修改日志","link":"/changelog"},{"title":"国内镜像","link":"https://pro-components.antdigital.dev"}]},"sidebar":{"/components":[{"title":"组件","children":[{"title":"卡片","link":"/components/card"}]}],"/docs":[{"title":"文档","children":[{"title":"介绍","link":"/docs/introduce"}]}]}};
const _2_level_nav_available = true;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return (
    <SiteContext.Provider value={context}>
      {outlet}
    </SiteContext.Provider>
  );
}
